[tools]
python = "3.12.14"

[env]
# auto venv activation; refer https://mise.jdx.dev/mise-cookbook/python.html
_.python.venv = { path = ".venv", create = true }

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "python -m pip install --no-cache-dir -U -r requirements.txt --prefer-binary"